version: 1.0
variables:
  baseUrl: https://api-load.stage.yoma.world

  kcBaseUrl: https://keycloak.stage.yoma.world
  kcRealm: loadtest
  kcUsername: test
  kcPassword: password
  kcClientID: account
  kcClientSecret: verysecret
